[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-stargazing"
version = "0.1.5"
description = "This is a mcp server Calculate celestial object positions and rise/set times"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Henry Gong", email = "zhao.gong@outlook.com" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Astronomy",
]
dependencies = [
    "fastmcp",
    "astropy>=5.0",
    "pytz",
    "numpy",
    "astroquery",
    "rasterio",
    "tzlocal",
    "geopy",
    "stargazing-place-finder>=0.3.0"
]

[project.scripts]
mcp-stargazing = "src.main:main"

[project.urls]
Homepage = "https://github.com/StarGazer1995/mcp-stargazing"
Issues = "https://github.com/StarGazer1995/mcp-stargazing/issues"

[tool.setuptools.packages.find]
include = ["src*"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
